site_name: 'English for Developers'
site_description: 'English phrases, idioms and words for non-native English developers'
repo_name: omu/english
repo_url: https://github.com/omu/english/tree/develop
copyright: 'Content on this site is licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC Attribution-ShareAlike 3.0 Unported</a> license.'
docs_dir: docs
markdown_extensions:
  - codehilite:
      linenums: false
  - extra
  - mdx_truly_sane_lists
  - pymdownx.superfences
theme:
  name: material
  language: en
  logo:
    icon: pages
  palette:
    primary: blue grey
    accent: indigo
plugins:
  - search:
      lang: en
extra:
  social:
    - type: github
      link: https://github.com/omu
    - type: linkedin
      link: https://linkedin.com/company/omu-baum